version: "3.3"
services:
  web:
    image: nginx
    ports:
    - 8080:80
    networks: 
    - my-network

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
    - mysql-data:/var/lib/mysql:rw
    networks: 
    - my-network

  python-app:
    build: .
    image: nachomillangarcia/python-flask
    ports:
    - 5000:5000
    command: ["python", "app.py"]
    networks: 
    - my-network

  ubuntu:
    image: ubuntu
    entrypoint: ["/bin/bash"]
    command: ["-c", "sleep 10000"]
    networks: 
    - my-network

volumes:
  mysql-data:

networks:
  my-network: