version: "3.3"
services:
  web:
    image: nginx
    ports:
    - 8080:80

  mysql:
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
    - mysql-data:/var/lib/mysql

  python-app:
    build: .
    image: nachomillangarcia/python-flask
    ports:
    - 5000:5000

volumes:
  mysql-data:
